### ISSUE TITLE
[新功能]reality可否添加grpc与h2版本的

### ISSUE THREAD

**Issue by qqyc** [fscarmen/sing-box#22]
rt

**Comment by fscarmen** [comment]
是可以加的，脚垫原则上每个协议只配最常用的，比如vless+ws，就不弄vless+gRPC了。reality那两个真有必要？

**Comment by qqyc** [comment]
> 是可以加的，脚垫原则上每个协议只配最常用的，比如vless+ws，就不弄vless+gRPC了。reality那两个真有必要？

reality+vision目前暂时没实现0rtt，grpc和h2版的可以，而且没有明确证据证明这样风险比vision更大

**Comment by fscarmen** [comment]
h2版的clash meta配置信息有吗？我怎么试都不行的
```
  - name: "vless-reality-h2"
    type: vless
    server: 34.172.218.1
    port: 10000
    uuid: b546f450-1dac-411c-83e7-4d9cd57a5dc9
    network: h2
    tls: true
    udp: true
    flow:
    client-fingerprint: chrome
    servername: addons.mozilla.org
    reality-opts:
      public-key: vXSMIs5dnS5C6dJYWztLaFV2CMOk3fv-OQxIfzyeC1g
      short-id: ""
```
